### ISSUE TITLE
This role cant handle remote postgres databases

### ISSUE THREAD

**Issue by nakomoto** [mrlesmithjr/ansible-guacamole#18]
Hi!

In defaults/main.yml you asking for guacamole_postgresql_db.host and guacamole_postgresql_db.port, but you dont use it in the tasks. You are trying to create a local database and this fails because there is no locally installed PostgreSQL

```
TASK [guacamole-role : config | Creating Guacamole DB] ***********************************************
fatal: [guacamole]: FAILED! => changed=false 
  module_stderr: |-
    Shared connection to 10.10.10.32 closed.
  module_stdout: |-
    sudo: unknown user: postgres
    sudo: error initializing audit plugin sudoers_audit
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

The same for `Creating Guacamole DB User` task and `Popluating DB` task and so on in `tasks/config.yml`

**Comment by stefanDeveloper** [comment]
I ran into the same issue, however, I could resolve it by running: `sudo apt install postgresql postgresql-client`.
After that I could use: `sudo -u postgres psql`

**Comment by stefanDeveloper** [comment]
My biggest problem was that I ran into the issue the issue:
```
fatal: [guacamole]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (psycopg2) on guacamole's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}
```

I could resolve it by adding the tasks:
```yaml
- name: install pip3
  apt: name=python3-pip state=present
  become: true

- name: Install psycopg2 for ansible to be able to create postgresql users
  pip: name=psycopg2-binary
  become: true
```
