### ISSUE TITLE
Failed to compile 1.5.2 version

### ISSUE THREAD

**Issue by roumano** [mrlesmithjr/ansible-guacamole#46]
**Describe the bug**
latest version of guacamole failed to compile, see https://lists.apache.org/thread/h5zql3zdov0ngh8kp9r3yppcprq5z1jf for more information about it

It's not a issue of this ansible role but as it's blocking install, it need to be addressed

**To Reproduce**
the tasks  `install | Compiling Guacamole Server` will faied due to this error : 
```
/usr/bin/ld: /home/sam/guacamole-server-1.5.4/src/libguac/.libs/libguac.so: undefined reference to `timer_delete'
/usr/bin/ld: /home/sam/guacamole-server-1.5.4/src/libguac/.libs/libguac.so: undefined reference to `timer_settime'
/usr/bin/ld: /home/sam/guacamole-server-1.5.4/src/libguac/.libs/libguac.so: undefined reference to `timer_create'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:563: guacd] Error 1
make[2]: Leaving directory '/home/sam/guacamole-server-1.5.4/src/guacd'
```

* OS Impacted (at least) : 
  * Debian Bullseye
  * Gentoo
  * OpenSUSE Leap 15.5 
* OS not impacted : 
  * Alpine Edge
  * Ubuntu 22.04 bases

**Additional context**
workarround is to use `LDFLAGS: '-lrt'` : 
But i'm not sure if it's a good idea to enable this everywhere , ...
```
- name: install | Configuring Guacamole Server Build # noqa no-changed-when
  ansible.builtin.command: ./configure --with-init-dir=/etc/init.d --disable-guacd
  args:
    chdir: "{{ guacamole_src_dir + '/guacamole-server-' + guacamole_version }}"
  become: true
  register: _guacamole_config_server_build
  when: not _guacamole_server_installed['stat']['exists'] or extract.changed
# Workarround for this bug in 1.5.4 : https://lists.apache.org/thread/h5zql3zdov0ngh8kp9r3yppcprq5z1jf
  environment:
    LDFLAGS: '-lrt'
```
