### ISSUE TITLE
Failure to download MySQL Connector

### ISSUE THREAD

**Issue by Chiggins** [mrlesmithjr/ansible-guacamole#69]
**Describe the bug**
Unable to download `https://cdn.mysql.com//Downloads/Connector-J/mysql-connector-j-8.0.33.tar.gz` as it returns a 404. [Line](https://github.com/mrlesmithjr/ansible-guacamole/blob/master/defaults/main.yml#L31) defining the URL, and [line](https://github.com/mrlesmithjr/ansible-guacamole/blob/master/tasks/config.yml#L83) downloading the package.

**To Reproduce**
Added the following to a playbook `site.yml`:

```
- name: Guacamole
  hosts: guac_server
  strategy: free
  become: true
  roles:
    - { role: geerlingguy.mysql }
  tasks:
    - name: apt update host
      ansible.builtin.apt:
        pkg: python3-mysqldb
        update_cache: yes
    - name: Include ansible-guacamole
      ansible.builtin.include_role:
        name: mrlesmithjr.guacamole
```

**Expected behavior**
Expected the MySQL Connector to download and the successful installation of Guacmole.

**Screenshots**
```
TASK [mrlesmithjr.guacamole : config | Downloading MySQL Connector] ************************************************************************************************************************************************
fatal: [10.0.0.3]: FAILED! => {"changed": false, "msg": "Failure downloading https://cdn.mysql.com//Downloads/Connector-J/mysql-connector-j-8.0.33.tar.gz, HTTP Error 404: Not Found"}
```

```
❯ curl -v https://cdn.mysql.com//Downloads/Connector-J/mysql-connector-j-8.0.33.tar.gz
* Host cdn.mysql.com:443 was resolved.
* IPv6: 2600:1407:b800:4ae::1d68, 2600:1407:b800:4b1::1d68
* IPv4: 23.61.42.21
*   Trying [2600:1407:b800:4ae::1d68]:443...
* Connected to cdn.mysql.com (2600:1407:b800:4ae::1d68) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256 / [blank] / UNDEF
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: C=US; ST=California; L=Redwood City; O=Oracle Corporation; CN=cdn.mysql.com
*  start date: Feb  9 00:00:00 2025 GMT
*  expire date: Feb 11 23:59:59 2026 GMT
*  subjectAltName: host "cdn.mysql.com" matched cert's "cdn.mysql.com"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=GeoTrust RSA CA 2018
*  SSL certificate verify ok.
* using HTTP/1.x
> GET //Downloads/Connector-J/mysql-connector-j-8.0.33.tar.gz HTTP/1.1
> Host: cdn.mysql.com
> User-Agent: curl/8.7.1
> Accept: */*
>
* Request completely sent off
< HTTP/1.1 404 Not Found
< Accept-Ranges: bytes
< Content-Length: 10
< Server: AkamaiNetStorage
< Date: Wed, 16 Apr 2025 17:45:33 GMT
< Connection: keep-alive
< Content-Type: application/x-tar-gz
<
Not found
* Connection #0 to host cdn.mysql.com left intact
```

**Desktop (please complete the following information):**
 - OS: Debian bookwork/sid
